name: medata_integration
channels:
  - anaconda
  - conda-forge
dependencies:
  - conda-forge::python
  - conda-forge::pip
  - conda-forge::numpy
  - conda-forge::openpyxl
  - conda-forge::pandas
  - conda-forge::jupyterlab
  - conda-forge::ipython
  - conda-forge::xlrd
  - conda-forge::psycopg2
  - conda-forge::sqlalchemy
  - conda-forge::matplotlib
  - conda-forge::plotly
  # Linters and documentation
  - conda-forge::flake8
  - conda-forge::rope
  - conda-forge::black
  - conda-forge::pep257
  - conda-forge::mypy
  - conda-forge::pydocstyle
